default: &default
  adapter: postgresql
  pool: 5
  username: username
  password: password
  host:     <%= ENV['IP'] %>

development:
  <<: *default
  database: myledger_development

test:
  <<: *default
  database: myledger_test

production:
  <<: *default
  database: myledger_production
